# Generated by Django 3.2 on 2023-05-11 18:41

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("recipes", "0002_auto_20230511_1502"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ingredientinrecipe",
            name="amount",
            field=models.PositiveSmallIntegerField(
                validators=[
                    django.core.validators.MinValueValidator(
                        1, "Колличество ингредиента в рецепте не должно быть менее 1."
                    )
                ],
                verbose_name="Колличество ингредиента в данном рецепте.",
            ),
        ),
    ]
