# Generated by Django 3.2 on 2023-05-13 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0008_auto_20230512_2327'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='favorite',
            name='recipes_favorite_unique',
        ),
        migrations.RemoveConstraint(
            model_name='shoppingcart',
            name='recipes_shoppingcart_unique',
        ),
        migrations.AddField(
            model_name='favorite',
            name='is_shopping_cart',
            field=models.BooleanField(default=False, editable=False),
        ),
        migrations.AddField(
            model_name='shoppingcart',
            name='is_shopping_cart',
            field=models.BooleanField(default=False, editable=False),
        ),
        migrations.AddConstraint(
            model_name='favorite',
            constraint=models.UniqueConstraint(fields=('user', 'recipe', 'is_shopping_cart'), name='recipes_favorite_unique'),
        ),
        migrations.AddConstraint(
            model_name='shoppingcart',
            constraint=models.UniqueConstraint(fields=('user', 'recipe', 'is_shopping_cart'), name='recipes_shoppingcart_unique'),
        ),
    ]
